import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

import matter from 'gray-matter';

const DOCS_DIR = path.resolve(__dirname, '../../..', 'docs');
const SKILL_TEMPLATE_PATH = path.resolve(DOCS_DIR, 'templates/skill_template.md');
const OUTPUT_DIR = path.resolve(__dirname, '../../..', 'skills');
const REFERENCES_DIR = path.resolve(DOCS_DIR, 'references');

function parseFrontMatter(content: string): { name: string; description: string; body: string } {
  const result = matter(content);
  const data: any = result.data;
  return {
    name: data.name || '',
    description: data.description || '',
    body: result.content.trim(),
  };
}

function formatDescription(description: string): string {
  if (description.includes('\n')) {
    const lines = description.split('\n');
    const indentedLines = lines.map((line) => {
      if (line.trim() === '') return '';
      return '  ' + line;
    });
    return indentedLines.join('\n');
  }
  return '  ' + description;
}

function main() {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  } else {
    const files = fs.readdirSync(OUTPUT_DIR);
    for (const file of files) {
      if (file !== 'package.json') {
        fs.rmSync(path.join(OUTPUT_DIR, file), { recursive: true, force: true });
      }
    }
  }

  const autoGeneratedMarkerPath = path.join(OUTPUT_DIR, '.AUTO_GENERATED.md');
  let autoGeneratedContent: string | null = null;
  if (fs.existsSync(autoGeneratedMarkerPath)) {
    autoGeneratedContent = fs.readFileSync(autoGeneratedMarkerPath, 'utf-8');
  }

  const template = fs.readFileSync(SKILL_TEMPLATE_PATH, 'utf-8');
  const sourceContent = fs.readFileSync(path.join(DOCS_DIR, 'trace_analysis.md'), 'utf-8');
  const { name, description, body } = parseFrontMatter(sourceContent);

  const formattedDescription = formatDescription(description);

  const skillContent = template
    .replace('{{SKILL_NAME}}', name)
    .replace('{{SKILL_DESCRIPTION}}', formattedDescription)
    .replace('{{SKILL_INSTRUCTION}}', body);

  fs.writeFileSync(path.join(OUTPUT_DIR, 'SKILL.md'), skillContent);
  console.log('Generated SKILL.md');

  if (autoGeneratedContent) {
    fs.writeFileSync(autoGeneratedMarkerPath, autoGeneratedContent);
    console.log('Preserved .AUTO_GENERATED.md');
  }

  const refDir = path.join(OUTPUT_DIR, 'references');
  if (!fs.existsSync(refDir)) {
    fs.mkdirSync(refDir, { recursive: true });
  }

  if (fs.existsSync(REFERENCES_DIR)) {
    const analyzerFiles = fs.readdirSync(REFERENCES_DIR);
    analyzerFiles.forEach((file) => {
      if (file.endsWith('.md')) {
        const sourcePath = path.join(REFERENCES_DIR, file);
        const destPath = path.join(refDir, file);
        fs.copyFileSync(sourcePath, destPath);
        console.log(`Copied analyzer: ${file}`);
      }
    });
  } else {
    console.log('References directory not found:', REFERENCES_DIR);
  }

  console.log('\nExecuting bundle...');
  try {
    execSync('pnpm run bundle-trace-query', {
      stdio: 'inherit',
      cwd: path.resolve(__dirname, '..'),
    });
    console.log('Bundle completed successfully!');
  } catch (error: any) {
    console.error('Error executing bundle!');
    if (error.stdout) {
      console.error('stdout:', error.stdout.toString());
    }
    if (error.stderr) {
      console.error('stderr:', error.stderr.toString());
    }
    console.error('Error:', error);
    process.exit(1);
  }

  const scriptsDestDir = path.join(OUTPUT_DIR, 'scripts');

  if (!fs.existsSync(scriptsDestDir)) {
    fs.mkdirSync(scriptsDestDir, { recursive: true });
  }

  const bundles = ['trace_query.bundle.cjs', 'trace_record.bundle.cjs', 'shared.bundle.cjs'];

  bundles.forEach((bundleFileName) => {
    const bundleSourcePath = path.resolve(__dirname, '..', 'dist', 'bundles', bundleFileName);
    const bundleDestPath = path.join(scriptsDestDir, bundleFileName);
    if (fs.existsSync(bundleSourcePath)) {
      fs.copyFileSync(bundleSourcePath, bundleDestPath);
      console.log(`Copied ${bundleFileName} to: ${bundleDestPath}`);
    } else {
      console.error('Bundle file not found:', bundleSourcePath);
      process.exit(1);
    }
  });
}

main();
